### ISSUE TITLE
Roulette is not a real roulette

### ISSUE THREAD

**Issue by DBanaszewski** [DBanaszewski/dbot-issue-tracker#2]
Our roulette is not a real roulette - we must rebuild our roulette system.

**Comment by DBanaszewski** [comment]
For some time, when we are fixing roulette, we'll delete this command from bot.

**Comment by DBanaszewski** [comment]
We must create a small discussion about this game - we'll remove this game from our bot.

**Comment by BitCrack** [comment]
Do you have any ideas on how to allow users to earn bananas?
Roulette was the only way so far, if you remove it without making a replacement you might as well remove the whole economy system in my opinion.

**Comment by DBanaszewski** [comment]
Yes, users can earn bananas by be active on our server.
We can add other games such as coin toss, etc.

**Comment by DBanaszewski** [comment]
The roulette idea is abandoned.
