### ISSUE TITLE
Add graylist support

### ISSUE THREAD

**Issue by DBanaszewski** [DBanaszewski/dbot-issue-tracker#6]
We must add a graylist support - some users abused functions from bot.

**Comment by DBanaszewski** [comment]
Done.

**Comment by BitCrack** [comment]
I beg you please change the name to blacklist

**Comment by DBanaszewski** [comment]
On blacklist we have got banned users, on graylist we have got users without normal permissions (only writing and reading) - blacklist isn't good offer.

**Comment by BitCrack** [comment]
Ah, alright
